account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),

    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),

    path('login/',
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'),
]

galleryproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('', include('account.urls')),

    path('password_reset/', 
         auth_views.PasswordResetView.as_view(
             template_name = "password_reset.html"),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name = "password_reset_sent.html"),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name = "password_reset_form.html"),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name = "password_reset_done.html"),
         name='password_reset_complete'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
    )

photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'

urlpatterns = [
    path('',
         views.CoverView.as_view(),
         name='cover'),

    path('index/',
         views.IndexView.as_view(),
         name='index'),

    path('post/',
         views.CreatePhotoView.as_view(),
         name='post'),

    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),

    path('photos/<int:category>',
         views.CategoryView.as_view(),
         name='photos_cat'),

    path('tags/<int:tag>',
         views.TagView.as_view(),
         name='tags_cat'),

    path('user-list/<int:user>',
         views.UserView.as_view(),
         name='user_list'),

    path('photo-detail/<int:pk>',
         views.DetailView.as_view(),
         name='photo_detail'),

    path('mypage/',
         views.MypageView.as_view(),
         name='mypage'),

    path('photo/<int:pk>/delete/',
         views.PhotoDeleteView.as_view(),
         name='photo_delete'),

    path('contact/',
         views.ContactView.as_view(),
         name='contact'),
]

photo/models.py
from django.db import models
from account.models import CustomUser

# Create your models here.
class Category(models.Model):
    title = models.CharField(
        verbose_name='カテゴリ',
        max_length=20
    )

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(
        verbose_name='タグ',
        max_length=20
    )

    def __str__(self):
        return self.title


class PhotoPost(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )

    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
    )

    title = models.CharField(
        verbose_name='タイトル',
        max_length=200
    )

    comment = models.TextField(
        verbose_name='コメント'
    )

    image1 = models.ImageField(
        verbose_name='イメージ１',
        upload_to = 'photos'
    )

    image2 = models.ImageField(
        verbose_name='イメージ２',
        upload_to='photos',
        blank=True,
        null=True
    )

    image3 = models.ImageField(
        verbose_name='イメージ３',
        upload_to='photos',
        blank=True,
        null=True
    )

    tag1 = models.ForeignKey(
        Tag,
        verbose_name='タグ1',
        on_delete=models.PROTECT,
        related_name='tag1_posts',
        blank=True,
        null=True
    )

    tag2 = models.ForeignKey(
        Tag,
        verbose_name='タグ2',
        on_delete=models.PROTECT,
        related_name='tag2_posts',
        blank=True,
        null=True
    )

    tag3 = models.ForeignKey(
        Tag,
        verbose_name='タグ3',
        on_delete=models.PROTECT,
        related_name='tag3_posts',
        blank=True,
        null=True
    )

    tag4 = models.ForeignKey(
        Tag,
        verbose_name='タグ4',
        on_delete=models.PROTECT,
        related_name='tag4_posts',
        blank=True,
        null=True
    )

    tag5 = models.ForeignKey(
        Tag,
        verbose_name='タグ5',
        on_delete=models.PROTECT,
        related_name='tag5_posts',
        blank=True,
        null=True
    )

    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )

    def __str__(self):
        return self.title

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost
from django import forms


class PhotoPostForm(ModelForm):
    class Meta:
        model = PhotoPost
        fields = ['category', 'title', 'comment', 'image1', 'image2', 'image3', 'tag1', 'tag2', 'tag3', 'tag4', 'tag5']


class ContactForm(forms.Form):
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['placeholder'] = \
            'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'

        self.fields['email'].widget.attrs['placeholder'] = \
            'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'

        self.fields['title'].widget.attrs['placeholder'] = \
            'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'

        self.fields['message'].widget.attrs['placeholder'] = \
            'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'

photo/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView
from django.views.generic import DetailView, DeleteView, FormView
from django.urls import reverse_lazy
from .forms import PhotoPostForm, ContactForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import PhotoPost
from django.contrib import messages
from django.core.mail import EmailMessage
from django.db.models import Q
from dotenv import load_dotenv
import os

load_dotenv()

class CoverView(TemplateView):
    template_name = 'cover.html'


class IndexView(ListView):
    template_name = 'index.html'
    queryset = PhotoPost.objects.order_by('-posted_at')
    paginate_by = 9


@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    form_class = PhotoPostForm
    template_name = "post_photo.html"
    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)


class PostSuccessView(TemplateView):
    template_name = 'post_success.html'


class CategoryView(ListView):
    template_name = 'index.html'
    paginate_by = 9

    def get_queryset(self):
        category_id = self.kwargs['category']
        categories = PhotoPost.objects.filter(
            category=category_id
        ).order_by('-posted_at')
        return categories


class TagView(ListView):
    template_name = 'index.html'
    paginate_by = 9

    def get_queryset(self):
        tag_id = self.kwargs['tag']
        tags = PhotoPost.objects.filter(
            Q(tag1=tag_id) | Q(tag2=tag_id) | Q(tag3=tag_id)
            | Q(tag4=tag_id)| Q(tag5=tag_id)
        ).order_by('-posted_at')
        return tags
    

class UserView(ListView):
    template_name = 'index.html'
    paginate_by = 9

    def get_queryset(self):
        user_id = self.kwargs['user']
        user_list = PhotoPost.objects.filter(
            user=user_id
        ).order_by('-posted_at')
        return user_list


class DetailView(DetailView):
    template_name = 'detail.html'
    model = PhotoPost


class MypageView(ListView):
    template_name = 'mypage.html'
    paginate_by = 9

    def get_queryset(self):
        queryset = PhotoPost.objects.filter(
            user=self.request.user
        ).order_by('-posted_at')
        return queryset


class PhotoDeleteView(DeleteView):
    model = PhotoPost
    template_name = 'photo_delete.html'
    success_url = reverse_lazy('photo:mypage')

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('photo:contact')

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = 'お問い合わせ：{}'.format(title)
        message = \
            '送信者名：{0}\n メールアドレス：{1}\n タイトル：{2}\n メッセージ：\n{3}' \
            .format(name, email, title, message)
        
        from_email = os.environ.get('EMAIL_USER')
        to_list = os.environ.get('EMAIL_USER')
        
        message = EmailMessage(subject=subject,
                               body=message,
                               from_email=from_email,
                               to=[to_list],
                               )
        message.send()
        messages.success(
            self.request, 'お問い合わせは正常に送信されました。'
        )
        return super().form_valid(form)

photo/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.84.0">

  <title>{% block title %}{% endblock %}</title>

  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin" />
  <link rel="preload" as="style"
    href="https://fonts.googleapis.com/css2?family=Arimo:wght@400;600;700&amp;display=swap" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Arimo:wght@400;600;700&amp;display=swap"
    media="print" onload="this.media='all'" />
  <noscript>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Arimo:wght@400;600;700&amp;display=swap" />
  </noscript>
  <link href="{% static 'assets/css/bootstrap.min.css' %}?ver=1.2.0" rel="stylesheet">
  <link href="{% static 'assets/css/font-awesome/css/all.min.css' %}?ver=1.2.0" rel="stylesheet">
  <link href="{% static 'assets/css/main.css' %}?ver=1.2.0" rel="stylesheet">
  <link rel="icon" type="image/x-icon" href="{% static 'assets/img/flashlight.png' %}" />

  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <style>
    .pp-header {
      background-color: #FFFFFB; /* Set the background color of the header */
    }

    .navbar {
      background-color: #FFFFFB; /* Set the background color of the navbar */
    }

    .navbar-brand {
      /* Add this style to adjust the color of the navbar brand */
      color: #343a40; /* Set the text color to a dark color for better visibility */
    }

    .navbar-nav .nav-link {
      color: #343a40; /* Set the text color of the navbar links */
    }

    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .back-to-top-img {
      opacity: 0.5;
      /* Set default opacity */
      transition: opacity 0.3s ease;
      /* Add a smooth transition effect */
    }

    .back-to-top-link:hover .back-to-top-img {
      opacity: 1;
      /* Set opacity to 1 on hover */
    }

    .custom-footer {
      background-color: #f0f0f0;
      /* Replace with the desired color */
    }
  </style>
</head>

<body>

  <header>
    <div class="pp-header">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a href="{% url 'photo:index' %}">
            <img src="{% static 'assets/img/logo.png' %}" alt="Logo" width="80" height="80">
          </a>
          <a class="navbar-brand" href="{% url 'photo:index' %}">
            300,000km/s
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
            aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarHeader">
            <ul class="navbar-nav ms-auto">
              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{% url 'photo:index' %}">ホーム</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'photo:mypage' %}">マイページ</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'account:logout' %}">ログアウト</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'password_reset' %}">パスワードのリセット</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'photo:contact' %}">問い合わせ</a></li>
              {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'photo:index' %}">ホーム</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'account:signup' %}">サインアップ</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'account:login' %}">ログイン</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'photo:contact' %}">問い合わせ</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </header>

  <main class="bg-light">
    {% block contents %}{% endblock %}
  </main>

  <footer class="text-muted py-5 custom-footer">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#" class="back-to-top-link">
          <img src="{% static 'assets/img/backToTop.png' %}" alt="Back to top" class="img-fluid back-to-top-img"
            width="30" height="30">
        </a>
      </p>
      <p class="mb-1">
        © 2023 Beamshot Gallery
      </p>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
</body>

</html>

photo/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contact Me{% endblock %}

<!-- Main Content-->
{% block contents %}
<main class="bg-light">
    <div class="container pp-section">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                {% if messages %}
                <div class="alert alert-info mt-4">
                    <ul class="list-unstyled" style="list-style: none; margin: 0;">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                            {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}


                <div class="card p-4 shadow-sm" style="border-radius: 15px;">
                    <strong>連絡を取りたいですか？
                        以下のフォームに記入してメッセージを送信してください。
                        できるだけ早くご連絡します。</strong>
                </div>

                <div class="my-5">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-floating">
                            <div class="form-group floating-label-form-group controls">
                                {{ field.label_tag }}
                                {{ field }}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        {% endfor %}

                        <br>
                        <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

photo/templates/cover.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Beam Gallery</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">

    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/flashlight.png' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
            margin: 0;
            padding: 0;
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            text-align: center;
            background-image: url('{% static 'assets/img/cover.jpg' %}');
            background-size: cover;
            color: white;
        }

        .title {
            font-size: 3rem;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .cover-button {
            background-color: transparent;
            color: white;
            border: 2px solid #FFD700;
            /* Grooming border color (replace with your preferred color) */
            padding: 10px 20px;
            /* Adjust padding as needed */
            margin-top: 40px;
            text-decoration: none;
            transition: background-color 0.3s ease, color 0.3s ease;
            /* Add a smooth transition effect */
        }

        /* Hover effect for the button on the cover page */
        .cover-button:hover {
            background-color: #FFD700;
            /* Change to your preferred color on hover */
            color: white;
        }

        h1 {
            font-size: 1.8rem;
            /* Adjust the font size as needed */
        }
    </style>
</head>

<body>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-10 col-md-8 mx-auto d-flex flex-column align-items-center">
                <h1 class="fw-bold text-white text-start">
                    ねぇ、秒速30万キロメートルなんだって。<br>
                    <br>
                    ：えっ、なに？<br>
                    <br>
                    光の伝播スピード。秒速30万キロメートル。
                </h1>
                <a href="{% url 'photo:index' %}" class="btn cover-button">Light Up</a>
            </div>
        </div>
    </section>
</body>

</html>

photo/templates/detail.html
{% extends 'base.html' %}
{% block title %}Photo Detail{% endblock title %}


{% block contents %}
<br>
<div class="container">
    <div class="container pp-section">
        <div class="h3 font-weight-normal" id="titleAndImage">
            <h2>{{ object.title }}</h2>
            <br>
            <p><img src="{{ object.image1.url }}" class="img-fluid" alt="{{ object.title }}">
            </p>

            {% if object.image2 %}
            <p><img src="{{ object.image2.url }}" class="img-fluid" alt="{{ object.title }}">
            </p>
            {% endif %}

            {% if object.image3 %}
            <p><img src="{{ object.image3.url }}" class="img-fluid" alt="{{ object.title }}"></p>
            {% endif %}
        </div>

        <div class="row mt-5" id="sidebarAndComment">
            <div class="col-md-3" id="sidebar">
                <div class="h5">Category</div>
                <p><a class="mr-1 badge badge-primary" href="{% url 'photo:photos_cat' category=object.category.id %}"
                        style="text-decoration: none;">
                        {{ object.category.title }}
                    </a>
                </p>

                <div class="h5">Tags</div>
                <div class="mb-4">
                    {% if object.tag1 %}
                    <a class="mr-1 badge badge-secondary" href="{% url 'photo:tags_cat' tag=object.tag1.id %}"
                        style="text-decoration: none;">
                        {{ object.tag1.title }}
                    </a>
                    {% endif %}

                    {% if object.tag2 %}
                    <a class="mr-1 badge badge-success" href="{% url 'photo:tags_cat' tag=object.tag2.id %}"
                        style="text-decoration: none;">
                        {{ object.tag2.title }}
                    </a>
                    {% endif %}

                    {% if object.tag3 %}
                    <a class="mr-1 badge badge-danger" href="{% url 'photo:tags_cat' tag=object.tag3.id %}"
                        style="text-decoration: none;">
                        {{ object.tag3.title }}
                    </a>
                    {% endif %}

                    {% if object.tag4 %}
                    <a class="mr-1 badge badge-success" href="{% url 'photo:tags_cat' tag=object.tag4.id %}"
                        style="text-decoration: none;">
                        {{ object.tag4.title }}
                    </a>
                    {% endif %}

                    {% if object.tag5 %}
                    <a class="mr-1 badge badge-success" href="{% url 'photo:tags_cat' tag=object.tag5.id %}"
                        style="text-decoration: none;">
                        {{ object.tag5.title }}
                    </a>
                    {% endif %}
                </div>

                <div class="h5 pt-4">User</div>
                <p><a class="mr-1 badge badge-dark" href="{% url 'photo:user_list' user=object.user.id %}"
                        style="text-decoration: none;">
                        {{ object.user.username }}
                    </a></p>

                <div class="h5 pt-4">Posted At</div>
                <p>{{ object.posted_at }}</p>
            </div>

            <div class="col-md-9">
                <p style="white-space: pre-line;">{{ object.comment }}</p>
            </div>
        </div>

        {% if request.user == object.user %}
        <br>
        <hr>
        <div class="container text-center mt-3">
            <form method="POST" style="display: inline;">
                <a href="{% url 'photo:photo_delete' object.pk %}"
                    class="btn btn-primary my-2">削除する</a>
            </form>
        </div>
        {% endif %}

    </div>
    <div class="pp-section"></div>
</div>
{% endblock %}

photo/templates/mypage.html
{% extends "base.html" %}
{% block title %}My Page{% endblock title %}

{% block contents %}
{% if user.is_authenticated %}
<br>
<div style="text-align: center;">
    <h4>{{ user.username }}さんのマイページ</h4>
    {% if object_list.count == 0 %}
    <p>{{ user.username }}さんの投稿はありません</p>
    {% else %}
    <p>投稿<strong>{{ object_list.count }}</strong>件</p>
    {% endif %}
    <a href="{% url 'photo:post' %}" class="btn btn-primary">投稿する</a>
</div>
<hr>
{% endif %}

{% include "photos_list.html" %}

{% include "pagination.html" %}

{% endblock contents %}

photo/templates/photo_delete.html
{% extends "base.html" %}
{% block title %}Photo Delete{% endblock title %}

    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <form method="POST">
                    <br>
                    <p>削除してもいいですか？</p>
                    {% csrf_token %}
                    <button class="btn btn-primary my-2"
                    type="submit">削除</button>
                    <a href="{% url 'photo:photo_detail' object.pk %}"
                        class="btn btn-secondary my-2">キャンセル</a>
                </form>
            </div>
        </div>
    </div>
    {% endblock contents %}

photo/templates/photos_list.html
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for record in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ record.image1.url }}"
                  class="bd-placeholder-img card-img-top img-fluid"
                  width="100%" height="225"
                  xmlns="http://www.w3.org/2000/svg"
                  role="img" aria-label="Placeholder: Thumbnail"
                  preserveAspectRatio="xMidYMid slice"
                  focusable="false">
                  <title>Placeholder</title>
                  <rect width="100%" height="100%" fill="#55595c"/>
            </img>

            <div class="card-body">
              <p class="card-text">
                {{ record.title }}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button"
                          class="btn btn-sm btn-primary"
                          onclick="location.href='{% url 'photo:photo_detail' record.pk %}'">
                          Detail</button>
                  <button type="button"
                          class="btn btn-sm btn-outline-success"
                          onclick="location.href='{% url 'photo:photos_cat' category=record.category.id %}'">
                          {{ record.category.title }}</button>
                </div>
                <a class="mr-1 badge badge-info" href="{% url 'photo:user_list' user=record.user.id %}"
                    style="text-decoration: none;">
                    {{ record.user.username }}
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

photo/templates/photos_title.html
{% load static %}

<style>
  .btn-gentle {
    background-color: #e0e0e0;
    /* Set a gentle background color */
    color: #333;
    /* Set a darker text color */
    border-color: #ccc;
    /* Set a border color */
    transition: box-shadow 0.3s ease;
    /* Add a smooth transition effect on box-shadow */
  }

  .btn-gentle:hover {
    background-color: #d0d0d0;
    /* Set a slightly darker background color on hover */
    color: #555;
    /* Set a slightly darker text color on hover */
    border-color: #bbb;
    /* Set a slightly darker border color on hover */
    box-shadow: 0 0 10px rgba(255, 255, 255, 0.7);
    /* Add a subtle box shadow on hover */
  }
</style>

<section class="py-5 text-center container"
          style="background-image: url('{% static 'assets/img/title.jpg' %}');
          background-size: 100% 100%;
          background-position: center;
          background-repeat: no-repeat;">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-bold text-white">Beam Gallery</h1>
      <p class="lead text-white">
        これは懐中電灯のビームショット写真のギャラリーです。
        お気軽にビームショット写真を投稿してください。
      </p>
      <p>
        {% if user.is_authenticated %}
        <a href="{% url 'photo:post' %}"
            class="btn btn-gentle my-2">投稿する</a>
        <a href="{% url 'account:logout' %}"
            class="btn btn-gentle my-2">ログアウト</a>

        {% else %}
        <a href="{% url 'account:signup' %}"
            class="btn btn-gentle my-2">今すぐサインアップ</a>
        <a href="{% url 'account:login' %}"
            class="btn btn-gentle my-2">登録済の方はログイン</a>
        {% endif %}
      </p>
    </div>
  </div>
</section>

photo/templates/post_success.html
{% extends "base.html" %}
{% block title %}Post Successful{% endblock title %}

    {% block contents %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4>投稿が完了しました！</h4>
                <br>
                <a class="mr-1" href="{% url 'photo:index' %}" style="text-decoration: none;">
                    ホームページへ</a>
            </div>
        </div>
    </div>
    <br>
    {% endblock contents %}